package MrJEditor.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EntityAssignmentType {
  std(".", "S"),
  num("N", "N"),
  excludeAfter("!", "!"),
  excludeAllNotEmpty("X!", "X!"),
  excludeAllEmpty("X_OPT!", "X_OPT!"),
  excludeAllSpecialChar("W!", "W!"),
  excludeAfterEmpty("=", "=");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EntityAssignmentType(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EntityAssignmentType> getConstants() {
    List<EntityAssignmentType> list = ListSequence.fromList(new LinkedList<EntityAssignmentType>());
    ListSequence.fromList(list).addElement(EntityAssignmentType.std);
    ListSequence.fromList(list).addElement(EntityAssignmentType.num);
    ListSequence.fromList(list).addElement(EntityAssignmentType.excludeAfter);
    ListSequence.fromList(list).addElement(EntityAssignmentType.excludeAllNotEmpty);
    ListSequence.fromList(list).addElement(EntityAssignmentType.excludeAllEmpty);
    ListSequence.fromList(list).addElement(EntityAssignmentType.excludeAllSpecialChar);
    ListSequence.fromList(list).addElement(EntityAssignmentType.excludeAfterEmpty);
    return list;
  }
  public static EntityAssignmentType getDefault() {
    return EntityAssignmentType.std;
  }
  public static EntityAssignmentType parseValue(String value) {
    if (value == null) {
      return EntityAssignmentType.getDefault();
    }
    if (value.equals(EntityAssignmentType.std.getValueAsString())) {
      return EntityAssignmentType.std;
    }
    if (value.equals(EntityAssignmentType.num.getValueAsString())) {
      return EntityAssignmentType.num;
    }
    if (value.equals(EntityAssignmentType.excludeAfter.getValueAsString())) {
      return EntityAssignmentType.excludeAfter;
    }
    if (value.equals(EntityAssignmentType.excludeAllNotEmpty.getValueAsString())) {
      return EntityAssignmentType.excludeAllNotEmpty;
    }
    if (value.equals(EntityAssignmentType.excludeAllEmpty.getValueAsString())) {
      return EntityAssignmentType.excludeAllEmpty;
    }
    if (value.equals(EntityAssignmentType.excludeAllSpecialChar.getValueAsString())) {
      return EntityAssignmentType.excludeAllSpecialChar;
    }
    if (value.equals(EntityAssignmentType.excludeAfterEmpty.getValueAsString())) {
      return EntityAssignmentType.excludeAfterEmpty;
    }
    return EntityAssignmentType.getDefault();
  }
}
