package MrJEditor.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum FormatType {
  extended("extended", "extended"),
  classical("classical", "classical");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private FormatType(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<FormatType> getConstants() {
    List<FormatType> list = ListSequence.fromList(new LinkedList<FormatType>());
    ListSequence.fromList(list).addElement(FormatType.extended);
    ListSequence.fromList(list).addElement(FormatType.classical);
    return list;
  }
  public static FormatType getDefault() {
    return FormatType.extended;
  }
  public static FormatType parseValue(String value) {
    if (value == null) {
      return FormatType.getDefault();
    }
    if (value.equals(FormatType.extended.getValueAsString())) {
      return FormatType.extended;
    }
    if (value.equals(FormatType.classical.getValueAsString())) {
      return FormatType.classical;
    }
    return FormatType.getDefault();
  }
}
