package MrJEditor.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum I18NLang {
  it("it", "it"),
  en("en", "en");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private I18NLang(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<I18NLang> getConstants() {
    List<I18NLang> list = ListSequence.fromList(new LinkedList<I18NLang>());
    ListSequence.fromList(list).addElement(I18NLang.it);
    ListSequence.fromList(list).addElement(I18NLang.en);
    return list;
  }
  public static I18NLang getDefault() {
    return I18NLang.it;
  }
  public static I18NLang parseValue(String value) {
    if (value == null) {
      return I18NLang.getDefault();
    }
    if (value.equals(I18NLang.it.getValueAsString())) {
      return I18NLang.it;
    }
    if (value.equals(I18NLang.en.getValueAsString())) {
      return I18NLang.en;
    }
    return I18NLang.getDefault();
  }
}
