package MrJEditor.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Opt {
  _("-", "-"),
  _OPT("_OPT", "_OPT");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private Opt(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<Opt> getConstants() {
    List<Opt> list = ListSequence.fromList(new LinkedList<Opt>());
    ListSequence.fromList(list).addElement(Opt._);
    ListSequence.fromList(list).addElement(Opt._OPT);
    return list;
  }
  public static Opt getDefault() {
    return Opt._;
  }
  public static Opt parseValue(String value) {
    if (value == null) {
      return Opt.getDefault();
    }
    if (value.equals(Opt._.getValueAsString())) {
      return Opt._;
    }
    if (value.equals(Opt._OPT.getValueAsString())) {
      return Opt._OPT;
    }
    return Opt.getDefault();
  }
}
