package MrJEditor.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptComment = createDescriptorForComment();
  /*package*/ final ConceptDescriptor myConceptElement = createDescriptorForElement();
  /*package*/ final ConceptDescriptor myConceptEntityAssignment = createDescriptorForEntityAssignment();
  /*package*/ final ConceptDescriptor myConceptEntityDeclaration = createDescriptorForEntityDeclaration();
  /*package*/ final ConceptDescriptor myConceptEntityReference = createDescriptorForEntityReference();
  /*package*/ final ConceptDescriptor myConceptEntitySetVar = createDescriptorForEntitySetVar();
  /*package*/ final ConceptDescriptor myConceptEntitySubstitution = createDescriptorForEntitySubstitution();
  /*package*/ final ConceptDescriptor myConceptEntityWithOpt = createDescriptorForEntityWithOpt();
  /*package*/ final ConceptDescriptor myConceptITextElement = createDescriptorForITextElement();
  /*package*/ final ConceptDescriptor myConceptOperation = createDescriptorForOperation();
  /*package*/ final ConceptDescriptor myConceptOperationList = createDescriptorForOperationList();
  /*package*/ final ConceptDescriptor myConceptOperationRef = createDescriptorForOperationRef();
  /*package*/ final ConceptDescriptor myConceptRule = createDescriptorForRule();
  /*package*/ final ConceptDescriptor myConceptRuleTest = createDescriptorForRuleTest();
  /*package*/ final ConceptDescriptor myConceptScript = createDescriptorForScript();
  /*package*/ final ConceptDescriptor myConceptScriptList = createDescriptorForScriptList();
  /*package*/ final ConceptDescriptor myConceptScriptName = createDescriptorForScriptName();
  /*package*/ final ConceptDescriptor myConceptTestDeep = createDescriptorForTestDeep();
  /*package*/ final ConceptDescriptor myConceptTestMatch = createDescriptorForTestMatch();
  /*package*/ final ConceptDescriptor myConceptTestWiki = createDescriptorForTestWiki();
  /*package*/ final ConceptDescriptor myConceptText = createDescriptorForText();
  /*package*/ final ConceptDescriptor myConceptTextElement = createDescriptorForTextElement();
  /*package*/ final ConceptDescriptor myConceptTrainDocCat = createDescriptorForTrainDocCat();
  /*package*/ final ConceptDescriptor myConceptTrainDocCatLine = createDescriptorForTrainDocCatLine();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptComment, myConceptElement, myConceptEntityAssignment, myConceptEntityDeclaration, myConceptEntityReference, myConceptEntitySetVar, myConceptEntitySubstitution, myConceptEntityWithOpt, myConceptITextElement, myConceptOperation, myConceptOperationList, myConceptOperationRef, myConceptRule, myConceptRuleTest, myConceptScript, myConceptScriptList, myConceptScriptName, myConceptTestDeep, myConceptTestMatch, myConceptTestWiki, myConceptText, myConceptTextElement, myConceptTrainDocCat, myConceptTrainDocCatLine);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Comment:
        return myConceptComment;
      case LanguageConceptSwitch.Element:
        return myConceptElement;
      case LanguageConceptSwitch.EntityAssignment:
        return myConceptEntityAssignment;
      case LanguageConceptSwitch.EntityDeclaration:
        return myConceptEntityDeclaration;
      case LanguageConceptSwitch.EntityReference:
        return myConceptEntityReference;
      case LanguageConceptSwitch.EntitySetVar:
        return myConceptEntitySetVar;
      case LanguageConceptSwitch.EntitySubstitution:
        return myConceptEntitySubstitution;
      case LanguageConceptSwitch.EntityWithOpt:
        return myConceptEntityWithOpt;
      case LanguageConceptSwitch.ITextElement:
        return myConceptITextElement;
      case LanguageConceptSwitch.Operation:
        return myConceptOperation;
      case LanguageConceptSwitch.OperationList:
        return myConceptOperationList;
      case LanguageConceptSwitch.OperationRef:
        return myConceptOperationRef;
      case LanguageConceptSwitch.Rule:
        return myConceptRule;
      case LanguageConceptSwitch.RuleTest:
        return myConceptRuleTest;
      case LanguageConceptSwitch.Script:
        return myConceptScript;
      case LanguageConceptSwitch.ScriptList:
        return myConceptScriptList;
      case LanguageConceptSwitch.ScriptName:
        return myConceptScriptName;
      case LanguageConceptSwitch.TestDeep:
        return myConceptTestDeep;
      case LanguageConceptSwitch.TestMatch:
        return myConceptTestMatch;
      case LanguageConceptSwitch.TestWiki:
        return myConceptTestWiki;
      case LanguageConceptSwitch.Text:
        return myConceptText;
      case LanguageConceptSwitch.TextElement:
        return myConceptTextElement;
      case LanguageConceptSwitch.TrainDocCat:
        return myConceptTrainDocCat;
      case LanguageConceptSwitch.TrainDocCatLine:
        return myConceptTrainDocCatLine;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForComment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "Comment", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff61bafeL);
    b.class_(false, false, false);
    b.super_("MrJEditor.structure.Element", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff602336L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059431678");
    b.prop("commentText", 0x155a47bdff61baffL, "1538621104059431679");
    b.alias("//");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "Element", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff602336L);
    b.class_(false, false, false);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059327286");
    b.prop("lineNumber", 0x4c10d49d36b6edL, "21410603586729709");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntityAssignment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "EntityAssignment", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L);
    b.class_(false, false, false);
    b.super_("MrJEditor.structure.EntityDeclaration", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L);
    b.parent(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059574804");
    b.prop("type", 0x4c10d49d515887L, "21410603588475015");
    b.prop("numWord", 0x4c10d49d515889L, "21410603588475017");
    b.prop("predefined", 0x4c10d49e53c3d1L, "21410603605410769");
    b.aggregate("format", 0x4c10d49d51584fL).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L).optional(true).ordered(true).multiple(true).origin("21410603588474959").done();
    b.aggregate("exclude", 0x4c10d49d515851L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L).optional(true).ordered(true).multiple(true).origin("21410603588474961").done();
    b.alias("<>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntityDeclaration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "EntityDeclaration", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L);
    b.class_(false, false, false);
    b.super_("MrJEditor.structure.Element", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff602336L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059109441");
    b.prop("name", 0x4c10d49d68595eL, "21410603589982558");
    b.prop("value", 0x155a47bdff5cd079L, "1538621104059109497");
    b.alias("#");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntityReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "EntityReference", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63e96aL);
    b.class_(false, false, false);
    b.super_("MrJEditor.structure.EntityWithOpt", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x48081dcc6022dc52L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059574634");
    b.alias("$$");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntitySetVar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "EntitySetVar", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0xd75d12e392f3960L);
    b.class_(false, false, false);
    b.super_("MrJEditor.structure.EntityDeclaration", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L);
    b.parent(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/969911291226306912");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntitySubstitution() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "EntitySubstitution", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff62c107L);
    b.class_(false, false, false);
    b.super_("MrJEditor.structure.EntityWithOpt", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x48081dcc6022dc52L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059498759");
    b.alias("##");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEntityWithOpt() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "EntityWithOpt", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x48081dcc6022dc52L);
    b.class_(false, false, false);
    b.super_("MrJEditor.structure.TextElement", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff62c106L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/5190431334167927890");
    b.prop("optional", 0x48081dcc6022dc53L, "5190431334167927891");
    b.prop("possibleName", 0x4c10d49decdbe4L, "21410603598666724");
    b.associate("name", 0x48081dcc602861e2L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L).optional(true).origin("5190431334168289762").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForITextElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "ITextElement", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L);
    b.interface_();
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059574917");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOperation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "Operation", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2d7a6f14L);
    b.class_(false, false, false);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/2976269855645921044");
    b.prop("method", 0x294dd5aa2d7a6f17L, "2976269855645921047");
    b.prop("args", 0x294dd5aa2dc9f552L, "2976269855651132754");
    b.aggregate("elements", 0x294dd5aa2da4ddd5L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L).optional(true).ordered(true).multiple(true).origin("2976269855648701909").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOperationList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "OperationList", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2d7c98f7L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/2976269855646062839");
    b.aggregate("Elements", 0x294dd5aa2d7c98f8L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2d7a6f14L).optional(true).ordered(true).multiple(true).origin("2976269855646062840").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOperationRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "OperationRef", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2d7c98c7L);
    b.class_(false, false, false);
    b.parent(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/2976269855646062791");
    b.associate("oper", 0x294dd5aa2d7c98caL).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2d7a6f14L).optional(true).origin("2976269855646062794").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "Rule", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL);
    b.class_(false, false, false);
    b.super_("MrJEditor.structure.Element", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff602336L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059109502");
    b.prop("ruleNumber", 0x4c10d49d3a6f03L, "21410603586973443");
    b.prop("level", 0x155a47bdff5cd07fL, "1538621104059109503");
    b.prop("type", 0x155a47bdff5cd081L, "1538621104059109505");
    b.prop("botImg", 0x155a47bdff5cd0a2L, "1538621104059109538");
    b.aggregate("comments", 0xd75d12e3a35bc76L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff61bafeL).optional(true).ordered(true).multiple(true).origin("969911291243510902").done();
    b.aggregate("match", 0x155a47bdff5e8308L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L).optional(true).ordered(true).multiple(true).origin("1538621104059220744").done();
    b.aggregate("precond", 0x155a47bdff64934fL).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L).optional(true).ordered(true).multiple(true).origin("1538621104059618127").done();
    b.aggregate("preEval", 0x48081dcc601ef836L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L).optional(true).ordered(true).multiple(true).origin("5190431334167672886").done();
    b.aggregate("response", 0x48081dcc601ef83cL).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L).optional(true).ordered(true).multiple(true).origin("5190431334167672892").done();
    b.aggregate("postEval", 0x48081dcc601ef843L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L).optional(true).ordered(true).multiple(true).origin("5190431334167672899").done();
    b.aggregate("tests", 0x155a47bdff5e2385L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e0215L).optional(true).ordered(true).multiple(true).origin("1538621104059196293").done();
    b.aggregate("subRules", 0x155a47bdff61d3dcL).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL).optional(true).ordered(true).multiple(true).origin("1538621104059438044").done();
    b.alias("r");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRuleTest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "RuleTest", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e0215L);
    b.class_(false, false, false);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059187733");
    b.prop("type", 0x155a47bdff5e0216L, "1538621104059187734");
    b.prop("input", 0x155a47bdff5e0218L, "1538621104059187736");
    b.prop("lastMatched", 0x294dd5aa2e55add4L, "2976269855660289492");
    b.prop("resultTime", 0x294dd5aa2edb8f6dL, "2976269855669063533");
    b.prop("lastError", 0x294dd5aa2f4cc186L, "2976269855676481926");
    b.prop("matchedVars", 0x2e1143b5c887237L, "207469303023825463");
    b.aggregate("listOfAssignments", 0x155a47bdff5e0d35L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L).optional(true).ordered(true).multiple(true).origin("1538621104059190581").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScript() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "Script", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07bL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059109499");
    b.prop("extension", 0x557cb712c26a3a3aL, "6159999681535031866");
    b.prop("format", 0x48081dcc603803c3L, "5190431334169314243");
    b.prop("showRuleNumber", 0x294dd5aa2d38798fL, "2976269855641598351");
    b.aggregate("Elements", 0x155a47bdff5cd07cL).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff602336L).optional(true).ordered(true).multiple(true).origin("1538621104059109500").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScriptList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "ScriptList", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2c6a643aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/2976269855628092474");
    b.prop("extension", 0x294dd5aa2c95f75fL, "2976269855630948191");
    b.aggregate("scripts", 0x294dd5aa2c790289L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2c790270L).optional(true).ordered(true).multiple(true).origin("2976269855629050505").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForScriptName() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "ScriptName", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2c790270L);
    b.class_(false, false, false);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/2976269855629050480");
    b.associate("script", 0x294dd5aa2c790271L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07bL).optional(true).origin("2976269855629050481").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTestDeep() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "TestDeep", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x53c537e75df7a487L);
    b.class_(false, false, true);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/6036292342413501575");
    b.prop("testSentence", 0x53c537e75df7a488L, "6036292342413501576");
    b.prop("outputConcept", 0x53c537e75df7a48aL, "6036292342413501578");
    b.prop("secondConcept", 0x196d17c1ccd4d438L, "1832146744542286904");
    b.prop("language", 0x53c537e75e1cfeafL, "6036292342415949487");
    b.prop("trainingFilePath", 0x196d17c1cc26c9edL, "1832146744530881005");
    b.prop("trainedFilePath", 0x196d17c1cc26c9f2L, "1832146744530881010");
    b.prop("messages", 0x196d17c1cc73e87fL, "1832146744535935103");
    b.prop("score", 0x196d17c1cc82433eL, "1832146744536875838");
    b.prop("secondScore", 0x196d17c1ccd4d441L, "1832146744542286913");
    b.prop("difference", 0x3b762dab12ae2134L, "4284662308265664820");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTestMatch() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "TestMatch", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2beea0c8L);
    b.class_(false, false, true);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/2976269855619981512");
    b.prop("match", 0x294dd5aa2beea0c9L, "2976269855619981513");
    b.prop("notExcapedMatch", 0x294dd5aa2bf9820fL, "2976269855620694543");
    b.prop("input", 0x294dd5aa2beea0cbL, "2976269855619981515");
    b.aggregate("output", 0x294dd5aa2c0e1739L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL).optional(true).ordered(true).multiple(true).origin("2976269855622043449").done();
    b.aggregate("parsedInput", 0x294dd5aa2bff6288L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L).optional(true).ordered(true).multiple(true).origin("2976269855621079688").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTestWiki() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "TestWiki", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x7ab76e63c687f59bL);
    b.class_(false, false, true);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/8842657768176874907");
    b.prop("text", 0x7ab76e63c687f59cL, "8842657768176874908");
    b.prop("output", 0x7ab76e63c687f59eL, "8842657768176874910");
    b.aggregate("items", 0x31ae58917983ee95L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL).optional(true).ordered(true).multiple(true).origin("3579896135638314645").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "Text", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL);
    b.class_(false, false, false);
    b.super_("MrJEditor.structure.TextElement", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff62c106L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059220734");
    b.prop("txt", 0x155a47bdff5e82ffL, "1538621104059220735");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTextElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "TextElement", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff62c106L);
    b.class_(false, false, false);
    b.parent(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea85L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/1538621104059498758");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTrainDocCat() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "TrainDocCat", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x53c537e75d220bf5L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/6036292342399503349");
    b.prop("filterConcept", 0x53c537e75d52306eL, "6036292342402658414");
    b.prop("filterContent", 0x53c537e75d8fc33bL, "6036292342406693691");
    b.prop("language", 0x53c537e75df7abcaL, "6036292342413503434");
    b.aggregate("docCatLines", 0x53c537e75d220bf8L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x53c537e75d21bb6bL).optional(true).ordered(true).multiple(true).origin("6036292342399503352").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTrainDocCatLine() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MrJEditor", "TrainDocCatLine", 0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x53c537e75d21bb6bL);
    b.class_(false, false, false);
    b.origin("r:bca74589-3665-4bdb-8f51-dc6d16b97340(MrJEditor.structure)/6036292342399482731");
    b.prop("label", 0x53c537e75d21bb6eL, "6036292342399482734");
    b.aggregate("examples", 0x53c537e75d220bd1L).target(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL).optional(true).ordered(true).multiple(true).origin("6036292342399503313").done();
    return b.create();
  }
}
