package MrJEditor.editor;

/*Generated by MPS */

import java.io.File;

public class CentralMemo {
  private static CentralMemo instance = null;
  private File docCatTrainedFile;
  private File docCatTrainingFile;

  public File getDocCatTrainedFile() {
    return docCatTrainedFile;
  }
  public void setDocCatTrainedFile(File docCatTrainedFile) {
    this.docCatTrainedFile = docCatTrainedFile;
  }

  public File getDocCatTrainingFile() {
    return docCatTrainingFile;
  }
  public void setDocCatTrainingFile(File docCatTrainingFile) {
    this.docCatTrainingFile = docCatTrainingFile;
  }


  private CentralMemo() {
  }
  public static CentralMemo getInstance() {
    if (instance == null) {
      instance = new CentralMemo();
    }
    return instance;
  }
}
