package MrJEditor.editor;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class UIUtils {
  public static boolean doElementContain(String filter, List<SNode> elements) {
    boolean result = false;
    for (SNode e : ListSequence.fromList(elements)) {
      if (SPropertyOperations.getString(e, MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL, 0x155a47bdff5e82ffL, "txt")).contains(filter)) {
        result = true;
        break;
      }
    }
    return result;
  }
}
