package MrJEditor.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.actions.descriptor.PastePostProcessor;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "MrJEditor";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (Arrays.binarySearch(stringSwitchCases_tpto26_a0a0a0c, concept.getName())) {
        case 0:
          return Collections.<NodeFactory>singletonList(new Factories.NodeFactory_1538621104059808852());
        case 1:
          return Collections.<NodeFactory>singletonList(new Factories.NodeFactory_2976269855642441740());
        case 2:
          return Collections.<NodeFactory>singletonList(new Factories.NodeFactory_5190431334167083003());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

  @Override
  public boolean hasBuilders() {
    return false;
  }
  @Override
  public Collection<PastePostProcessor> getPastePostProcessors() {
    return Arrays.asList(new PastePostProcessor[]{new RuleHandlers_PastePostProcessor_0()});
  }
  private static String[] stringSwitchCases_tpto26_a0a0a0c = new String[]{"Rule", "Script", "Text"};
}
