package main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_2976269855632341094(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_6159999681535093371(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_6159999681535097445(final PropertyMacroContext _context) {
    return "." + SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07bL, 0x557cb712c26a3a3aL, "extension"));
  }
  public static Object propertyMacro_GetPropertyValue_5190431334164495655(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L, 0x4c10d49d68595eL, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5190431334164500078(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L, 0x155a47bdff5cd079L, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_21410603589074059(final PropertyMacroContext _context) {
    if (!(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("S")) && !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("N"))) {
      return SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S");
    } else {
      return "";
    }
  }
  public static Object propertyMacro_GetPropertyValue_21410603589135159(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("N") && SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515889L, "numWord")) > 0) {
      return "" + SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515889L, "numWord"));
    } else {
      return "";
    }

  }
  public static Object propertyMacro_GetPropertyValue_5190431334164522896(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L, 0x4c10d49d68595eL, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5190431334167246409(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x48081dcc6022dc52L, 0x48081dcc602861e2L, "name")), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L, 0x4c10d49d68595eL, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5190431334164541442(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x48081dcc6022dc52L, 0x48081dcc6022dc53L, "optional"), "-").equals("_OPT")) {
      return "_OPT";
    } else {
      return "";
    }
  }
  public static Object propertyMacro_GetPropertyValue_5190431334164527923(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x48081dcc6022dc52L, 0x48081dcc602861e2L, "name")), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L, 0x4c10d49d68595eL, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5190431334164546562(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x48081dcc6022dc52L, 0x48081dcc6022dc53L, "optional"), "-").equals("_OPT")) {
      return "_OPT";
    } else {
      return "";
    }
  }
  public static Object propertyMacro_GetPropertyValue_5190431334164979637(final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e0215L, 0x155a47bdff5e0216L, "type"), "S");
  }
  public static Object propertyMacro_GetPropertyValue_5190431334164982949(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e0215L, 0x155a47bdff5e0218L, "input"));
  }
  public static Object propertyMacro_GetPropertyValue_5190431334164551154(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff61bafeL, 0x155a47bdff61baffL, "commentText"));
  }
  public static Object propertyMacro_GetPropertyValue_5190431334165014957(final PropertyMacroContext _context) {
    if (SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x155a47bdff5cd07fL, "level")) >= 1) {
      return "" + SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x155a47bdff5cd07fL, "level"));
    } else {
      return "";
    }
  }
  public static Object propertyMacro_GetPropertyValue_5190431334167770311(final PropertyMacroContext _context) {
    if (SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x155a47bdff5cd0a2L, "botImg"), null) != null) {
      return SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x155a47bdff5cd0a2L, "botImg"), null);
    } else {
      return "";
    }
  }
  public static Object propertyMacro_GetPropertyValue_969911291239880575(final PropertyMacroContext _context) {
    return "";
  }
  public static Object propertyMacro_GetPropertyValue_5190431334165227157(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL, 0x155a47bdff5e82ffL, "txt"));
  }
  public static Object propertyMacro_GetPropertyValue_969911291226628569(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd041L, 0x4c10d49d68595eL, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_2976269855656750445(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2d7c98c7L, 0x294dd5aa2d7c98caL, "oper")), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x294dd5aa2d7a6f14L, 0x294dd5aa2d7a6f17L, "method"));
  }
  public static Object propertyMacro_GetPropertyValue_6036292342407854524(final PropertyMacroContext _context) {
    return SPropertyOperations.getString((SNodeOperations.cast(SNodeOperations.getParent(_context.getNode()), MetaAdapterFactory.getConcept(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x53c537e75d21bb6bL, "MrJEditor.structure.TrainDocCatLine"))), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x53c537e75d21bb6bL, 0x53c537e75d21bb6eL, "label"));
  }
  public static Object propertyMacro_GetPropertyValue_6036292342418337009(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_6036292342419003615(final PropertyMacroContext _context) {
    return ".train";
  }
  public static boolean ifMacro_Condition_2976269855632346371(final IfMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).matches("^00.*");
  }
  public static boolean ifMacro_Condition_21410603589497915(final IfMacroContext _context) {
    return !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("N")) && ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d51584fL, "format"))).isNotEmpty();
  }
  public static boolean ifMacro_Condition_21410603589472735(final IfMacroContext _context) {
    return !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("N"));
  }
  public static boolean ifMacro_Condition_21410603589499174(final IfMacroContext _context) {
    return !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("N")) && ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d51584fL, "format"))).isNotEmpty();
  }
  public static boolean ifMacro_Condition_21410603589453557(final IfMacroContext _context) {
    return !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("N")) && !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("S")) && ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515851L, "exclude"))).isNotEmpty();
  }
  public static boolean ifMacro_Condition_21410603589405057(final IfMacroContext _context) {
    return !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("N")) && !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("S"));
  }
  public static boolean ifMacro_Condition_21410603589454881(final IfMacroContext _context) {
    return !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("N")) && !(SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515887L, "type"), "S").equals("S")) && ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515851L, "exclude"))).isNotEmpty();
  }
  public static boolean ifMacro_Condition_969911291227544853(final IfMacroContext _context) {
    return !(SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49e53c3d1L, "predefined")));
  }
  public static boolean ifMacro_Condition_969911291231651847(final IfMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x155a47bdff5cd07fL, "level")) > 0;
  }
  public static boolean ifMacro_Condition_969911291231948171(final IfMacroContext _context) {
    return (SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x48081dcc601ef843L, "postEval")) != null ? (SNodeOperations.isInstanceOf(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x48081dcc601ef843L, "postEval"))).last(), MetaAdapterFactory.getConcept(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL, "MrJEditor.structure.Text")) && SPropertyOperations.getString((SNodeOperations.cast(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x48081dcc601ef843L, "postEval"))).last(), MetaAdapterFactory.getConcept(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL, "MrJEditor.structure.Text"))), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL, 0x155a47bdff5e82ffL, "txt")) != null ? !(SPropertyOperations.getString((SNodeOperations.cast(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x48081dcc601ef843L, "postEval"))).last(), MetaAdapterFactory.getConcept(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL, "MrJEditor.structure.Text"))), MetaAdapterFactory.getProperty(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5e82feL, 0x155a47bdff5e82ffL, "txt")).endsWith(";")) : false) : false);
  }
  public static Iterable<SNode> sourceNodesQuery_2976269855633007959(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07bL, 0x155a47bdff5cd07cL, "Elements"));
  }
  public static Iterable<SNode> sourceNodesQuery_21410603589489116(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d51584fL, "format"));
  }
  public static Iterable<SNode> sourceNodesQuery_21410603589432708(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff63ea14L, 0x4c10d49d515851L, "exclude"));
  }
  public static Iterable<SNode> sourceNodesQuery_5190431334165110529(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x155a47bdff5e2385L, "tests"));
  }
  public static Iterable<SNode> sourceNodesQuery_6661772324823124823(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0xd75d12e3a35bc76L, "comments"));
  }
  public static Iterable<SNode> sourceNodesQuery_5190431334165009257(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x155a47bdff64934fL, "precond"));
  }
  public static Iterable<SNode> sourceNodesQuery_5190431334165012926(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x155a47bdff5e8308L, "match"));
  }
  public static Iterable<SNode> sourceNodesQuery_5190431334167701738(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x48081dcc601ef836L, "preEval"));
  }
  public static Iterable<SNode> sourceNodesQuery_5190431334167709932(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x48081dcc601ef83cL, "response"));
  }
  public static Iterable<SNode> sourceNodesQuery_5190431334167711930(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x48081dcc601ef843L, "postEval"));
  }
  public static Iterable<SNode> sourceNodesQuery_5190431334165111556(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x155a47bdff5cd07eL, 0x155a47bdff61d3dcL, "subRules"));
  }
  public static Iterable<SNode> sourceNodesQuery_6036292342407859013(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x53c537e75d21bb6bL, 0x53c537e75d220bd1L, "examples"));
  }
  public static Iterable<SNode> sourceNodesQuery_6036292342411173497(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xe74e27ff1ed748b3L, 0x90700f0eab442068L, 0x53c537e75d220bf5L, 0x53c537e75d220bf8L, "docCatLines"));
  }
}
